version: 2.1
orbs:
  node: circleci/node@4.1.0
  gh-pages: sugarshin/gh-pages@0.0.6
executors:
  buildpack_deps:
    docker:
      - image: circleci/buildpack-deps
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: |
          node --version
          mkdir -p config && touch $_/local.js
          echo $FULL_CONFIG  > ./config/local.js
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  deploy-artisol:
    working_directory: ~/leopard
    docker:
      - image: instrumentisto/rsync-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:02:54:8b:a5:25:c3:91:88:6e:82:d5:1d:4a:43:4a"
      - attach_workspace:
          at: ~/leopard
      - run: |
          ls -la
      - deploy:
          name: rsync over SSH
          command: |
            rsync -r -e "ssh -o StrictHostKeyChecking=no" --delete-after ~/leopard/dist/ $SSH_USER@$SSH_HOST:$TARGET_DIR
      - run:
          command: >-
            curl --insecure -XPOST -H "Content-type: application/json" -d '{
            "@context": "https://schema.org/extensions",
            "@type": "MessageCard",
            "themeColor": "16C60C",
            "title": "Successfully Deployed",
            "text": "Leopard has been successfully built and deployed",
            "potentialAction": [
                {
                    "@type": "OpenUri",
                    "name": "Leopard Chat UI",
                    "targets": [
                        {
                            "os": "default",
                            "uri": "https://wi.presales.artificial-solutions.com/leopard-chat/#/"
                        }
                    ]
                },
                {
                    "@type": "OpenUri",
                    "name": "Diffs",
                    "targets": [
                        {
                            "os": "default",
                            "uri": "https://github.com/jolzee/leopard-chat-ui-teneo/commit/master"
                        }
                    ]
                },
                {
                    "@type": "OpenUri",
                    "name": "All Commits",
                    "targets": [
                        {
                            "os": "default",
                            "uri": "https://github.com/jolzee/leopard-chat-ui-teneo/commits/master"
                        }
                    ]
                },
                {
                    "@type": "OpenUri",
                    "name": "Releases",
                    "targets": [
                        {
                            "os": "default",
                            "uri": "https://github.com/jolzee/leopard-chat-ui-teneo/releases/"
                        }
                    ]
                },
                {
                    "@type": "OpenUri",
                    "name": "Documentation",
                    "targets": [
                        {
                            "os": "default",
                            "uri": "https://jolzee.gitbook.io/leopard/"
                        }
                    ]
                }
            ]}' $MS_TEAMS_WEBHOOK_URL

  deploy-gh-pages:
    executor: buildpack_deps
    working_directory: ~/leopard
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo " StrictHostKeyChecking no" >> ~/.ssh/config
      - attach_workspace:
          at: ~/leopard
      - gh-pages/deploy:
          ssh-fingerprints: "5b:02:54:8b:a5:25:c3:91:88:6e:82:d5:1d:4a:43:4a"

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
          context: leopard-presales-ctx
      - deploy-artisol:
          filters:
            branches:
              only: master
          context: leopard-presales-ctx
          requires:
            - build
      - deploy-gh-pages:
          filters:
            branches:
              only: master
          requires:
            - build
