version: 2.1
orbs:
  node: circleci/node@2.1.1
  gh-pages: sugarshin/gh-pages@0.0.6
  ms-teams: cloudradar-monitoring/ms-teams@1.0.0
executors:
  buildpack_deps:
    docker:
      - image: circleci/buildpack-deps
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      # - node/install:
      #     node-version: 12.16.3
      - run: |
          node --version
          mkdir -p config && touch $_/local.js
          echo $FULL_CONFIG  > ./config/local.js
      - node/install-packages
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy-artisol:
    working_directory: ~/leopard
    docker:
      - image: instrumentisto/rsync-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5b:02:54:8b:a5:25:c3:91:88:6e:82:d5:1d:4a:43:4a"
      - attach_workspace:
          at: ~/leopard
      - run: |
          ls -la
      - deploy:
          command: |
            rsync -r -e "ssh -o StrictHostKeyChecking=no" --delete-after ~/leopard/dist/ $SSH_USER@$SSH_HOST:$TARGET_DIR
      - ms-teams/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL
  deploy-gh-pages:
    executor: buildpack_deps
    working_directory: ~/leopard
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "Host *" > ~/.ssh/config
          echo " StrictHostKeyChecking no" >> ~/.ssh/config
      - attach_workspace:
          at: ~/leopard
      - gh-pages/deploy:
          ssh-fingerprints: "5b:02:54:8b:a5:25:c3:91:88:6e:82:d5:1d:4a:43:4a"

workflows:
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
          context: leopard-presales-ctx
      - deploy-artisol:
          filters:
            branches:
              only: master
          context: leopard-presales-ctx
          requires:
            - build
      - deploy-gh-pages:
          filters:
            branches:
              only: master
          requires:
            - build
